version: "3.9"

services:
  livekit:
    container_name: livekit
    image: livekit/livekit-server:latest
    command: --config /livekit.yaml --node-ip=127.0.0.1
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./livekit.yaml:/livekit.yaml
  node:
    container_name: node
    image: tushe2000/lc-api
    restart: unless-stopped
    ports:
      - "5000:5000"
  ui:
    container_name: ui
    image: tushe2000/lc-ui
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node
