services:
  api:
    container_name: api
#    build:
#      context: ./api
#      dockerfile: ./Dockerfile
    image: tushe2000/lc-api
    restart: unless-stopped
    ports:
      - 5000:5000
  ui:
    container_name: ui
#    build:
#      context: ./ui
#      dockerfile: ./Dockerfile
    image: tushe2000/lc-ui
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
#    volumes:
#      - ./ui:/app
#      - /app/node_modules
    depends_on:
      - api
  livekit:
    container_name: livekit
    image: livekit/livekit-server:latest
    command: --config /livekit.yaml --node-ip=18.195.118.143
    restart: unless-stopped
    ports:
      - 7880:7880
      - 7881:7881
      - 7882:7882/udp
    volumes:
      - ./livekit.yaml:/livekit.yaml
